title: dotnetthoughts
tagline: a dotnet developer's technical journal
description: a dotnet developer's technical journal
url: "https://dotnetthoughts.net"
disqus_shortname: dotnetthoughts
google_analytics: 'UA-12179122-1'
google_site_verification: gfDtT8jd3OHpmGe2VJwYDE7G9-xwmpbQVVugKEU-Kp
baseurl: "/"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /:title/
paginate: 7
page_excerpts: true
logo: /assets/logo.png
feed:
  posts_limit: 10
seo_paginator_message: dotnetthoughts | a dotnet developer's technical journal
author:
  twitter: anuraj
twitter:
  username: anuraj
  card: summary_large_image
social:
  name: Anuraj
  links:
    - https://twitter.com/anuraj
    - https://www.linkedin.com/in/anurajp
    - https://github.com/anuraj
compress_html:
  clippings: all
  comments: all
  endings: all